name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "Thank you for your pull request. However, you have submitted this PR on the Lara-elegant organization which is a read-only sub split of `lara-igniter/framework`. Please submit your PR on the https://github.com/lara-igniter/framework repository.<br><br>Thanks!"
